import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Container from '@mui/material/Container';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-TW">
      <body className={inter.className}>
        <Container maxWidth="sm">
          {children}
        </Container>
      </body>
    </html>
  );
}
